apiVersion: v1
kind: Pod
metadata:
  name: multi
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: web-container
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  - name: ftp-container
    image: almalinux:8
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    env:
    - name: FTP_USER
      value: admin
    - name: FTP_PASS
      value: password
    command: ["/bin/bash", "-c", "tail -f /dev/null"]  # Keep the container running
