apiVersion: v1
kind: Service
metadata:
  name: kuard-service
  labels:
    app: kuard
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kuard
  type: LoadBalancer
